# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /blog/:title

include: ['_pages', '_newsletter']

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile*", "*.sh", "lib"]
highlighter: rouge

encoding: UTF-8

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : "Foolscap: February 5–7, 2016, in Seattle, Washington"
tagline: "Join the conversation. Build the convention"
author :
  name : Electric Keet
  email : it@foolscap.org

landing_header_class: ""
landing:
  about: "What _is_ Foolscap?"
  register: "How do I register?"
  location: "When and where?"
  functions: "What is there to do?"
  commons: "The heart of Foolscap is the Commons."
  magicbox: "Share media at the Magic Book Box."
  hospitality: "Hospitality is our open kitchen."
  bazaar: "Check out the Bazaar."
  volunteer: "Volunteers make Foolscap happen."
  events: "What’s on the schedule?"
  writing: "Writing workshops."
  bite: "The _Bite of Foolscap_ banquet."
  auction: "Auction"
  share: "May I bring stuff to show or sell?"
  info: "What else should I know?"
  news: "What’s new this year?"
  goh: "Here’s our Guest of Honor.    "
  
css_assets: "../assets"
blog :
  logo : images/logo-full-3col-dark-0300x0100.png
  minilogo : images/logo-init-3col-0040x0050.png
  background : images/Foolscap-poster-800px.png

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
#url:  http://127.0.0.1:4000
production_url : http://ghpages-test.foolscap.org/foolscapcon.github.io.testbed/
development_url : http://127.0.0.1:4000
#production_url : http://ghpages-test.foolscap.org

gems: ["jekyll-sitemap"]


archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
atom_path : /atom.xml
rss_path : /rss.xml
